services:
  db:
    image: docker.secuscope.iranet.net/postgres:16.3-alpine3.20
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    container_name: asset-postgres-test
    ports:
      - $DATABASE_PORT:5432
    logging:
      options:
        max-size: 5m
