export const UserGroups: Record<string, string> = {
  NSS: 'پیاده‌سازی سرویس‌های پایه شبکه',
  'N-Internet&Intranet':
    'پشتیبانی و عملیات سامانه های فناوری اطلاعات و ارتباطات',
  'N-NiBN': 'پیاده‌سازی شبکه بین بانکی ',
  'N-BNI': 'پیاده‌سازی شبکه بانکی ',
  'N-DCI': 'پیاده‌سازی شبکه مراکز داده',
  'N-OSS': 'طراحی و توسعه سامانه های نرم افزاری شبکه',
  'N-SAT': 'شبکه فضایی و ارتباط با رگولاتوری',
  'N-Infrastructure': 'زیرساخت ارتباطی و مخابراتی ',
  'O-Hardware and Infrastructure Support': 'پشتیبانی سخت افزار و زیرساخت',
  'O-System Software Support': 'پشتیبانی نرم افزارهای سیستمی',
  'O-NPS Operation': 'عملیات NPS',
  'O-B3': 'عملیات 3',
  'O-Operation Monitoring': 'عملیات سیستم های پایشی و پیام رسان بانکی',
  'O-Intermediate Systems Operation': 'عملیات و پشتیبانی سیستم‌های واسط',
  'O-Business Intelligence': 'هوش تجاری',
  'O-Intra Banking System Operation': 'عملیات سیستم‌های بین بانکی',
  'O-Card Operation': 'عملیات کارت',
  'O-New Banking Operation': 'عملیات بانکداری نوین',
  EDW: 'داده های بانکی',
  'O-Mainframe Operation': 'پشتیبانی عملیات',
  'O-Fix Shaparak Reconciliation': 'رفع مغايرت شاپرک',
  'O-Fix Banking Reconciliation': 'رفع مغايرت بانکی',
  'O-Fix Intra Banking Reconciliation': 'رفع مغايرت بين بانکی',
  'O-Support And Applications': 'پشتیبانی و نرم افزارها',
  'HelpDesk-Software': 'امداد و  پشتيبانی نرم افزار 1',
  'HelpDesk-Network': 'امداد و پشتيبانی شبکه',
  'O-Centralized Banking Systems 1': 'عملیات سیستم های متمرکز بانکی 1',
  'O-Centralized Banking Systems 2': 'عملیات سیستم های متمرکز بانکی 2',
  SOC: 'عملیات امنیت',
};
